/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.view;

import project.model.entity.Person;
import project.model.dao.PersonDAOimpl;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

import project.model.dao.CustomerDAOimpl;


/**
 * Classe login_Jframe qui hérite de la classe JFrame
 * et qui permet l'affichage de la page de connexiuon 
 * @author Kévin
 */
public class Login_JFrame extends javax.swing.JFrame {

    private static CustomerDAOimpl custDAO;

    /**
     * Construcreur de la login_jframe
     */
    public Login_JFrame() {
        setVisible(true);
        initComponents();
        custDAO = new CustomerDAOimpl();
        this.setTitle("Burger Factory");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButton_register = new javax.swing.JButton();
        jLabel_logo = new javax.swing.JLabel();
        jLabel_fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 51, 51));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_email.setText("Email");
        jPanel2.add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 60, 30));

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_password.setText("Password");
        jPanel2.add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 90, 30));

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });
        jTextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEmailKeyPressed(evt);
            }
        });
        jPanel2.add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 170, 30));

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 170, 30));

        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_button.PNG"))); // NOI18N
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jButtonLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonLoginKeyPressed(evt);
            }
        });
        jPanel2.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 150, 50));

        jButton_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register_button.PNG"))); // NOI18N
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });
        jButton_register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_registerKeyPressed(evt);
            }
        });
        jPanel2.add(jButton_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 150, 50));

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 190));

        jLabel_fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_login_burger_with_icon.png"))); // NOI18N
        jPanel2.add(jLabel_fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    //Button login
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        //Se connecte soit en customer soit en employee
        loginCustomeroEmployee();
    }//GEN-LAST:event_jButtonLoginActionPerformed
    
    /**
     * Methode qui permet de reconnaitre si un utilisateur qui sa connecte 
     * est un customer ou un employe en checkant dans la base de donné
     */
    public void loginCustomeroEmployee() {
        try {
            int valid;
            //We get the password and the email written by the user
            String email = jTextEmail.getText();
            String password = String.valueOf(jPasswordField1.getPassword());

            //We create an object login to log the user if he is a customer or employee
            Person login = new Person();
            PersonDAOimpl pers = new PersonDAOimpl();
            valid = pers.customerOrAdminLogin(email, password);
            if (valid == 1 || valid == 2) {

                this.dispose();
                if (valid == 1) {
                    //Envoyer vers le jFrame de l'application d'achat des articles (cart)
                    try {
                        Cart_JFrame customer_cart = new Cart_JFrame(custDAO.find(email));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error launching cart's jframe");
                    }
                }
                if (valid == 2) {
                    //Envoyer vers le JFrame de l'application de management des admins (management articles)
                    try {
                        Employee_JFrame employeeApp = new Employee_JFrame();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error launching employee's jframe");
                    }
                }
            }
            jPasswordField1.setText("");

            //Appeler l'application cart
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error button login");
        }
    }
    //Button register
    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed

        registerOpen();
    }//GEN-LAST:event_jButton_registerActionPerformed


    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginCustomeroEmployee();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jTextEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginCustomeroEmployee();
        }
    }//GEN-LAST:event_jTextEmailKeyPressed

    private void jButtonLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginCustomeroEmployee();
        }
    }//GEN-LAST:event_jButtonLoginKeyPressed

    private void jButton_registerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_registerKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            registerOpen();
        }
    }//GEN-LAST:event_jButton_registerKeyPressed

    /**
     * Methode qui crée la frame register appellé si le client appuie sur le bouton register
     */
    public void registerOpen() {
         // TODO add your handling code here:
        try {
            //Appeler la fonction de fermeture de l'autre fenetre 
            this.dispose();
            //We call the next window to register the user
            Register_JFrame register = new Register_JFrame();
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButton_register;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_fond;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextEmail;
    // End of variables declaration//GEN-END:variables
}
