/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.view;

import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.text.DefaultCaret;
import java.util.Properties;
import javax.mail.Message;

import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;
import javax.mail.Authenticator;
import javax.mail.MessagingException;

/**
 * Classe Receipt_JDialog qui hérite de la classe JDialog 
 * et qui permet l'affichage du récapitulatif de commande lors 
 * du paiement de ce dernier.
 * @author Kévin
 */
public class Receipt_JDialog extends javax.swing.JDialog {

    private static String receipt;
    private static String email;
    private static int idsales;

    /**
     * Constructeur qui recoit en param la jframe parent (Cart_JFrame), 
     * en String le recu, son email, et l'id de la commande
     *
     * @param parent
     * @param modal
     * @param receipt
     */
    public Receipt_JDialog(java.awt.Frame parent, boolean modal, String receipt, String email, int idsales) {
        super(parent, modal);
        initComponents();
        this.setTitle("Burger Factory");
        this.setSize(430, 500);
        dontAutoScroll(jTextArea_Ticket2);
        this.receipt = receipt;
        this.email = email;
        this.idsales = idsales;
        jTextArea_Ticket2.setText(receipt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_cancel = new javax.swing.JButton();
        jButton_email = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Ticket2 = new javax.swing.JTextArea();
        jButton_imprim = new javax.swing.JButton();
        jButton_quiiter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton_cancel.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_parmail.png"))); // NOI18N
        jButton_email.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_parmail_entered.png"))); // NOI18N
        jButton_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_emailActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 400, 40, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea_Ticket2.setEditable(false);
        jTextArea_Ticket2.setColumns(20);
        jTextArea_Ticket2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea_Ticket2.setRows(5);
        jTextArea_Ticket2.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea_Ticket2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 260, 320));

        jButton_imprim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_imprim.png"))); // NOI18N
        jButton_imprim.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_imprim_entered.png"))); // NOI18N
        jButton_imprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imprimActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_imprim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 40, 40));

        jButton_quiiter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_sortir.png"))); // NOI18N
        jButton_quiiter.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_sortir_entered.png"))); // NOI18N
        jButton_quiiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quiiterActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_quiiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 400, 40, 40));

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thank you for ordering from Burger Factory!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 380, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Here is your order summary");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_imprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imprimActionPerformed

        try {
            jTextArea_Ticket2.print(null, null, false, null, null, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vous n'avez rien imprimer");
        }


    }//GEN-LAST:event_jButton_imprimActionPerformed

    private void jButton_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_emailActionPerformed

        sendEmail();
    }//GEN-LAST:event_jButton_emailActionPerformed

    private void jButton_quiiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quiiterActionPerformed
        try {
            //Fermeture de la fenêtre
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Problème lors de la fermeture de la fenêtre receipt");
        }
    }//GEN-LAST:event_jButton_quiiterActionPerformed

    /**
     * Methode qui permet d'envoyer un mail (ici le reçu de la commande) a
     * partir d'une boite d'envoie gmail
     */
    public void sendEmail() {

        String to_email = email;//email receveur
        final String from_email = "burgerfactorykfc@gmail.com";//email envoyeur
        String subject = "Receipt - Order n°" + idsales;//Objet du mail
        String host = "smtp.gmail.com";//host

        //On put les properties 
        Properties properties = System.getProperties();
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "587");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.debug", "true");
        properties.put("mail.store.protocol", "pop3");
        properties.put("mail.transport.protocol", "smtp");

        //On instancie la session pour se connecter au compte d'envoie
        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                //On return le mail et le mot de passe
                return new PasswordAuthentication("burgerfactorykfc@gmail.com", "wordmotdepasse123789");
            }
        });
        //On instancie en Mimemessage en envoyant en parametre la session
        MimeMessage msg = new MimeMessage(session);
        try {

            msg.setFrom(new InternetAddress(from_email)); //On set l'email de l'envoyeur
            msg.addRecipient(Message.RecipientType.TO, new InternetAddress(to_email)); //l'email du destinataire
            msg.setSubject(subject);//On set l'objet du mail
            msg.setText(jTextArea_Ticket2.getText());//On set le corps du mail dans ce cas le jTextarea du receipt
            Transport.send(msg);//On envoie le message
            JOptionPane.showMessageDialog(null, "An email has just been sent to you");

        } catch (MessagingException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error to send a email");
        }
    }

    /**
     * Recoit un jTextArea et empeche l'autoscroll jusqu'en bas
     *
     * @param jtext
     */
    public void dontAutoScroll(JTextArea jtext) {

        DefaultCaret caret = (DefaultCaret) jtext.getCaret();
        caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Receipt_JDialog dialog = new Receipt_JDialog(new javax.swing.JFrame(), true, receipt, email, idsales);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_email;
    private javax.swing.JButton jButton_imprim;
    private javax.swing.JButton jButton_quiiter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Ticket2;
    // End of variables declaration//GEN-END:variables
}
