 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.view;

import project.model.entity.Customer;
import project.model.dao.CustomerDAOimpl;
import javax.swing.JOptionPane;

/**
 * Classe Registe_JFrame qui hérite de la classe JFrame et 
 * qui permet l'affichage d'une interface pour s'enregistrer 
 * et créer un nouveau compte client
 * @author damie
 */
public class Register_JFrame extends javax.swing.JFrame {

    /**
     * Constructeur Register_JFrame
     */
    public Register_JFrame() 
    {
        initComponents();
        setVisible(true);
        this.setTitle("Burger Factory");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextMail = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFirstName = new javax.swing.JTextField();
        jTextLastName = new javax.swing.JTextField();
        jTextAdress = new javax.swing.JTextField();
        jTextZipCode = new javax.swing.JTextField();
        jTextCity = new javax.swing.JTextField();
        jTextPhoneNumber = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1018, 723));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Register");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setText("Email");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel5.setText("First name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel6.setText("Last name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel7.setText("Adress");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel8.setText("Zipcode");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel10.setText("City");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel11.setText("Phone number");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));
        jPanel3.add(jTextMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 160, -1));
        jPanel3.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 160, -1));
        jPanel3.add(jTextFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 160, -1));
        jPanel3.add(jTextLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 160, -1));
        jPanel3.add(jTextAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 160, -1));
        jPanel3.add(jTextZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 160, -1));
        jPanel3.add(jTextCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 160, -1));
        jPanel3.add(jTextPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 160, -1));

        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register_button.PNG"))); // NOI18N
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 140, 30));

        jButtonCancel.setBackground(new java.awt.Color(255, 153, 51));
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_button.jpg.png"))); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register_back.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 600));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jPanel2.setMinimumSize(new java.awt.Dimension(1018, 723));
        jPanel2.setPreferredSize(new java.awt.Dimension(1018, 723));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_login_burger_with_icon.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(1030, 823));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Button Register
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        try
        {
            //CustomerDAO custDao = new CustomerDAOImpl();
            Customer user = new Customer();
            
            user.setEmail(jTextMail.getText());
            user.setf_name(jTextFirstName.getText());
            user.setl_name(jTextLastName.getText());
            user.setAdress(jTextAdress.getText());
            user.setZipcode(Integer.parseInt(jTextZipCode.getText()));
            user.setCity(jTextCity.getText());
            user.setTel_nb(Integer.parseInt(jTextPhoneNumber.getText()));
            user.setPassword(String.valueOf(jPasswordField1.getPassword()));
            CustomerDAOimpl cust = new CustomerDAOimpl();
            cust.add(user);
            
            //Appeler la fonction close de la fenêtre
            this.dispose();
            //We send back the user to the login sytem
             Login_JFrame login =  new Login_JFrame();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error inside register Jframe?");

        }
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    //Button cancel
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        //Appeler la fonction close de la fenêtre
        this.dispose();
        //We send back the user to the login sytem
        Login_JFrame login = new Login_JFrame();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Register_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextAdress;
    private javax.swing.JTextField jTextCity;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextLastName;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JTextField jTextPhoneNumber;
    private javax.swing.JTextField jTextZipCode;
    // End of variables declaration//GEN-END:variables
}
